spring:
  cloud:
    stream:
      bindings:
        input:
          destination: marcopolo.marco
          group: polo
        output:
          destination: marcopolo.polo

      kafka:
        binder:
          brokers: localhost

