dataset:
  products:
    mc: 5.0
    burger: 6.5
    chrispy: 4.3



spring:
  datasource:
    url: jdbc:mysql://localhost/cashier?useSSL=false
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
